[package]
edition = "2018"
name = "infinitree-macros"
version = "0.1.0"

[dependencies]
proc-macro-crate = "1.0.0"
proc-macro-error = "1.0"
proc-macro2 = "1"
quote = "1"
syn = "1"

[dev-dependencies]
infinitree = { path = "../infinitree", version = "*"}

[lib]
proc-macro = true
