[package]
name = "infinitree-backends"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
description = "Embedded, encrypted database with tiered cache -- backends"
version = "0.9.2"
keywords = ["crypto", "database", "cache", "s3", "rocksdb"]
categories = ["database-implementations", "concurrency", "data-structures", "algorithms", "caching"]
homepage = "https://symmetree.dev"
repository = "https://github.com/symmetree-labs/infinitree"
license = "MIT OR Apache-2.0"
edition= "2021"

[features]
default = []
rustls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls-alpn"]

[dependencies]
infinitree = { version = "0.9.0", path = "../infinitree" }

serde = "1.0.159"
serde_derive = "1.0.159"

anyhow = "1.0.70"
scc = "1.4.3"
lru = "0.10.0"

rusty-s3 = "0.4.1"
reqwest = { version = "0.11.16", default-features = false }
tokio = { version = "1.27.0", default-features = false, features = ["rt", "sync"] }
futures = "0.3.28"

[dev-dependencies]
infinitree = { version = "0.9.0", path = "../infinitree", features = ["test"] }
tokio = { version = "1.27.0", default-features = false, features = ["rt", "sync", "macros", "rt-multi-thread"] }
hyper = { version = "0.14.25", features = ["server"] }
s3-server = "0.2.0"
