[package]
name = "infinitree-backends"
version = "0.8.1"
edition = "2021"

[features]
default = []
rustls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls-alpn"]

[dependencies]
infinitree = { version = "0.8.1", path = "../infinitree" }

serde = { version = "1.0.137" }
serde_derive = "1.0.137"

anyhow = "1.0.57"
scc = "0.7.1"
lru = "0.7.5"

rusty-s3 = { version = "0.3.0" }
reqwest = { version = "0.11.10", default-features = false }
tokio = { version = "1.18.2", default-features = false, features = ["rt", "sync"]}
futures = { version = "0.3.21" }

[dev-dependencies]
infinitree = { version = "0.8.1", path = "../infinitree", features = ["test"] }
tokio = { version = "1.18.2", default-features = false, features = ["rt", "sync", "macros", "rt-multi-thread"]}
hyper = { version = "0.14.18", features = ["server"] }
s3-server = "0.2.0"