[package]
name = "infinitree"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
description = "Embedded, encrypted database with tiered cache"
version = "0.6.0"
keywords = ["crypto", "database", "cache", "sqlite", "rocksdb"]
categories = ["database-implementations", "concurrency", "data-structures", "algorithms", "caching"]
homepage = "https://symmetree.dev"
repository = "https://github.com/symmetree-labs/infinitree"
license = "MIT OR Apache-2.0"
edition= "2021"
build = "build.rs"
readme="../README.md"

[features]
default = ["mmap", "s3", "native-tls"]
mmap = ["memmap2"]
s3 = ["futures", "tokio", "rust-s3"]
rustls = ["rust-s3/tokio-rustls-tls"]
native-tls = ["rust-s3/tokio-native-tls"]

# internal use only
_test = ["s3", "native-tls"]

[dependencies]
blake3 = "1"
getrandom = "0.2"
ring = "0.16"
rust-argon2 = "1.0"

lz4_flex = { version = "0.9.0", default-features = false , features = ["frame"] }

scc = "0.6.10"
flume = "^0.10"
lru = "0.7"
thiserror = "1.0"
anyhow = "1.0"
hex = "0.4"
parking_lot = "0.12"

serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_with = { version = "1.11" }
rmp-serde = "1.1.0"

secrecy = "0.8"
zeroize = "^1"

infinitree-macros = { version = "0.6.0", path = "../infinitree-macros" }

rust-s3 = { version="0.31.0", default_features = false, features = ["with-tokio"], optional = true }
tokio = { version = "^1", features = ["rt", "macros", "rt-multi-thread", "parking_lot"], optional = true }
futures = { version = "0.3", optional = true }

memmap2 = { version = "0.5", optional = true }

[dev-dependencies]
criterion = "0.3"
paste = "1.0"
hyper = { version = "0.14", features = ["server"] }
s3-server = "0.2"

[[bench]]
name = "bench"
harness = false
path = "../benches/bench.rs"
