[package]
name = "infinitree"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
description = "Embedded, encrypted database with tiered cache"
version = "0.8.1"
keywords = ["crypto", "database", "cache", "sqlite", "rocksdb"]
categories = ["database-implementations", "concurrency", "data-structures", "algorithms", "caching"]
homepage = "https://symmetree.dev"
repository = "https://github.com/symmetree-labs/infinitree"
license = "MIT OR Apache-2.0"
edition= "2021"
build = "build.rs"
readme="../README.md"

[features]
default = ["mmap", "s3", "native-tls"]
mmap = ["memmap2"]
s3 = ["futures", "tokio", "rusty-s3"]
rustls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls-alpn"]
test = []
# internal use only
_test = ["test", "s3", "native-tls"]

[dependencies]
blake3 = "1.3.1"
getrandom = "0.2.6"
ring = "0.16.20"
rust-argon2 = "1.0.0"

lz4_flex = { version = "0.9.3", default-features = false, features = ["frame"] }

scc = "0.7.1"
flume = "0.10.12"
lru = "0.7.5"
thiserror = "1.0.31"
anyhow = "1.0.57"
hex = "0.4.3"
parking_lot = "0.12.0"

serde = { version = "1.0.137", features = ["rc"] }
serde_derive = "1.0.137"
serde_with = "1.13.0"
rmp-serde = "1.1.0"

secrecy = "0.8.0"
zeroize = "1.5.5"

infinitree-macros = { version = "0.8.1", path = "../infinitree-macros" }

rusty-s3 = { version = "0.3.0", optional = true }
reqwest = { version = "0.11.10", default-features = false, optional = true }
tokio = { version = "1.18.2", features = ["rt", "macros", "rt-multi-thread", "parking_lot"], optional = true }
futures = { version = "0.3.21", optional = true }

memmap2 = { version = "0.5.3", optional = true }

[dev-dependencies]
criterion = "0.3.5"
paste = "1.0.7"
hyper = { version = "0.14.18", features = ["server"] }
s3-server = "0.2.0"

[[bench]]
name = "bench"
harness = false
path = "../benches/bench.rs"
