[package]
name = "infinitree"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
description = "Embedded, encrypted database with tiered cache"
version = "0.3.0"
keywords = ["crypto", "database", "cache", "sqlite", "rocksdb"]
categories = ["database-implementations", "concurrency", "data-structures", "algorithms", "caching"]
homepage = "https://symmetree.dev"
repository = "https://github.com/symmetree-labs/infinitree"
license = "MIT OR Apache-2.0"
edition= "2021"
build = "build.rs"
readme="../README.md"

[features]
default = ["mmap"]
mmap = ["memmap2"]
s3 = ["tokio", "rusoto_core", "rusoto_s3"]
rustls = ["rusoto_core/rustls", "rusoto_s3/rustls"]
native-tls = ["rusoto_core/native-tls", "rusoto_s3/native-tls"]

# internal use only
_test = ["s3", "native-tls"]

[dependencies]
blake2b_simd = "1"
getrandom = "0.2"
ring = "0.16"
rust-argon2 = "0.8"

lz4_flex = { version = "0.9.0", default-features = false , features = ["frame"] }

scc = "0.5"
flume = "^0.10"
lru = "0.7"
thiserror = "1.0"
anyhow = "1.0"
hex = "0.4"
parking_lot = "0.11"

serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_with = { version = "1.11" }
rmp-serde = "^0.15"

secrecy = "0.8"
zeroize = "^1"

infinitree-macros = { version = "0.3", path = "../infinitree-macros" }

rusoto_core = { version="0.47", default_features=false, optional = true }
rusoto_s3 = { version="0.47", default_features=false, optional = true }
tokio = { version = "^1", features = ["rt", "macros", "rt-multi-thread"], optional = true }
futures = "0.3"

memmap2 = { version = "0.5", optional = true}

[dev-dependencies]
criterion = "0.3"
paste = "1.0"

[[bench]]
name = "bench"
harness = false
path = "../benches/bench.rs"