[package]
name = "infinitree"
authors = ["Peter Parkanyi <p@symmetree.dev>"]
description = "Embedded, encrypted database with 3-tier cache"
version = "0.1.0"
keywords = ["crypto", "database", "cache", "sqlite", "rocksdb"]
categories = ["database-implementations", "concurrency", "data-structures", "algorithms", "caching"]
homepage = "https://symmetree.dev"
repository = "https://github.com/symmetree-labs/infinitree"
license = "MIT OR Apache-2.0"
edition= "2018"
build = "build.rs"

[features]
default = ["s3", "mmap"]
s3 = ["rusoto_core", "rusoto_s3", "tokio"]
mmap = ["memmap2"]
test = []

[dependencies]
blake2b_simd = "0.5"
getrandom = "0.2"
ring = "0.16"
rust-argon2 = "0.8"

lz4_flex = { version = "0.9.0", default-features = false , features = ["frame"] }

dashmap = "^4.0"
scc = "0.5"
flume = "^0.10"
lru = "0.7"
thiserror = "1.0"
anyhow = "1.0"
hex = "0.4"
parking_lot = "0.11"
chrono = { version = "0.4", features = ["serde"] }

serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
rmp-serde = "^0.15"

secrecy = "0.8"
zeroize = "^1"

infinitree-macros = { version = "0.1.0", path = "../infinitree-macros" }

rusoto_core = { version="0.47", default_features=false, features=["rustls"], optional = true }
rusoto_s3 = { version="0.47", default_features=false, features=["rustls"], optional = true }
tokio = { version = "^1", features = ["rt", "macros", "rt-multi-thread"], optional = true }

memmap2 = { version = "0.5", optional = true}

[dev-dependencies]
tokio = { version = "^1", features = ["rt", "macros", "rt-multi-thread"] }